POST http://localhost:3000/api/email/
content-type: application/json

{
        
    "nombre": "Miguel Nieto",
    "email": "miguelnieto.08@gmail.com",
    "asunto": "Alianzaa",
    "mensaje": "hola, quiero aliarme"

}