PUT http://localhost:3000/api/mascotas/id/6159176c91f3c527408d0506/
content-type: application/json

{
    "pet_name": "Puppy Nig",
    "pet_type": "perro",
    "pet_location": "Ibague",
    "pet_pic": "img/pets/pet-1.jpg",
    "pet_thum": "img/pets/thums/thums-1.jpg",
    "pet_phone": 234567,
    "pet_description": "Es muy bonito el perrito"
}
