POST http://localhost:3000/api/mascotas/
content-type: application/json

{
    "publisher_id": "61608a873ff1113d40794042",
    "pet_name" : "penny",
    "pet_type" : "gato",
    "pet_description" : "Mamífero doméstico de la familia de los cánidos , de tamaño , forma y pelaje muy diversos",
    "pet_phone" : 2091389021,
    "pet_location" : "Tolima"
}
