POST http://localhost:3000/api/mascotas/
content-type: application/json

{
    "publisher_id": "615e62036ffbd9aad838f1cf",
    "pet_name": "GATOMAN",
    "pet_type": "perro",
    "pet_location": "Ibague",
    "pet_pic": "img/pets/pet-1.jpg",
    "pet_thumb": "img/pets/thums/thums-1.jpg",
    "pet_phone": 234567,
    "pet_description": "Es muy bonito el perrito"
}